-- !Ups

ALTER TABLE "Car" ALTER COLUMN model SET NOT NULL;
ALTER TABLE "Car" ALTER COLUMN color SET NOT NULL;
ALTER TABLE "Car" ALTER COLUMN number SET NOT NULL;
ALTER TABLE "Car" ALTER COLUMN manufacture_year SET NOT NULL;

-- !Downs
ALTER TABLE "Car" ALTER COLUMN model DROP NOT NULL;
ALTER TABLE "Car" ALTER COLUMN color DROP NOT NULL;
ALTER TABLE "Car" ALTER COLUMN number DROP NOT NULL;
ALTER TABLE "Car" ALTER COLUMN manufacture_year DROP NOT NULL;
